## Consider the below code to answer further questions:
### import numpy as np
### list_ = [ ‘1’ , ’2’ , ‘3’ , ‘4’ , ‘5’ ]
### array_list = np.array(object = list_)
### Q1. Is there any difference in the data type of variables list_ and array_list? If there is then write a code
### to print the data types of both the variables.

In [19]:
import numpy as np
list_ = [ '1' , '2' , '3' , '4' , '5' ]
array_list = np.array(object = list_)

In [20]:
list_

['1', '2', '3', '4', '5']

In [21]:
array_list

array(['1', '2', '3', '4', '5'], dtype='<U1')

In [24]:

type(list_)

list

In [25]:
type(array_list)

numpy.ndarray

### yes, they are not of same datatypes one is list and other is array

## Q2. Write a code to print the data type of each and every element of both the variables list_ and arra_list.

In [27]:
for i in list_:
    print(type(i))

<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>


In [28]:
for i in array_list:
    print(type(i))

<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>


## Q3. Considering the following changes in the variable, array_list:
## array_list = np.array(object = list_, dtype = int)
## Will there be any difference in the data type of the elements present in both the variables, list_ and arra_list? If so then print the data types of each and every element present in both the variables, list_ and arra_list.

In [29]:
array_list = np.array(object = list_, dtype = int)

In [30]:
array_list

array([1, 2, 3, 4, 5])

In [31]:
type(array_list)

numpy.ndarray

In [32]:
for i in list_:
    print(type(i))

<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>


In [33]:
for i in array_list:
    print(type(i))

<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>


### After changing the dtype = int all the elements of array_list is now of integer datatypes

## Consider the below code to answer further questions:
## import numpy as np
## num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]
## num_array = np.array(object = num_list)
## Q4. Write a code to find the following characteristics of variable, num_array:
## (i) shape
## (ii) size

In [7]:
import numpy as np
num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]
num_array = np.array(object = num_list)

In [8]:
num_list

[[1, 2, 3], [4, 5, 6]]

In [9]:
num_array

array([[1, 2, 3],
       [4, 5, 6]])

In [10]:
num_array.shape

(2, 3)

In [11]:
num_array.size

6

## Q5. Write a code to create numpy array of 3*3 matrix containing zeros only, using a numpy array creation function.

In [1]:
import numpy as np


In [3]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

## Q6. Create an identity matrix of shape (5,5) using numpy functions?

In [5]:
np.eye(5,5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])